trancendering/ft_transcendence

srcs/game/game_module/BaseRoom.py, srcs/game/game_module/GameRoom.py, srcs/game/game_module/TournamentRoom.py, srcs/game/game_module/Vector.py, srcs/game/game_module/game_ctl.py, srcs/game/game_module/game_queue.py, srcs/game/game_module/socketio_server.py, srcs/game/game_module/tournament_queue.py
+ 공 계산 로직을 개선하였습니다
+ 주석을 일부 추가하였습니다
+ dequeue 버그와 바 위치 버그 등 일부 버그를 수정하였습니다
+ 에러 발생 시 모든 변수를 출력하는 디버그 구문을 추가하였습니다
=> Game debug

srcs/game/game_module/TournamentRoom.py, srcs/game/game_module/socketio_server.py
+ 토너먼트의 게임 결과를 블록체인에 올리는 코드를 추가했습니다
+ 사용자 입력 검증 버그를 일부 수정했습니다
=> Feat: 토너먼트 로그 블록체인 업로드 코드 추가

srcs/game/game_module/TournamentRoom.py
=> Fix: 토너먼트 로그 블록체인 업로드 코드 수정

srcs/docker-compose.yml, srcs/frontend/src/static/css/styles.css, srcs/frontend/src/views/components/record/mainButton.js, srcs/frontend/src/views/components/tournamentRecord.js, srcs/frontend/src/views/utils/languagePack.js, srcs/middleware/Dockerfile
1. 블록체인이 log 창에서 보여지도록 수정했습니다. 또
2. nginx도 docker compose 시간 단축하도록 마운트 처리
=> 1. 블록체인 log 보여지도록 2. docker compose nginx 

srcs/game/game_module/TournamentRoom.py
+ 토너먼트 결과를 블록체인에 올릴 때 비동기 코드가 작동하지 않는 에러를 수정하였습니다.
=> Fix: 토너먼트 로그 블록체인 업로드 비동기 수정

srcs/frontend/src/views/components/main/gameCustomizationModal.js
- gameCustomization.js - makeRandomName() 되돌림
=> Fix: gameCustomization.js - rollback makeRandomName()

srcs/frontend/src/views/components/game/gameCanvas.js, srcs/frontend/src/views/components/game/object/ball.js, srcs/frontend/src/views/components/game/object/index.js, srcs/frontend/src/views/components/game/object/nickname.js, srcs/frontend/src/views/components/game/object/score.js, srcs/frontend/src/views/components/main/gameCustomizationModal.js
- Game Customization 모듈 FancyBall 모드 추가
- ThreeJS 오브젝트 importing 방식 Index.js로 통합해서 importing 하도록 변경
- gameCustomizationModal.js - makeRandomName() 없이 인트라 닉네임으로 게임 플레이 테스팅 시 여러 명의 계정이 있어야 플레이가 가능하므로 주석을 해제함
=> Feat: frontend add ThreeJS fancyBall feature while gameplaying

srcs/frontend/src/store/actions/gameActionHandler.js
Fix: connectSocket에서 async 키워드 삭제
=> Fix: connectSocket에서 async 키워드 삭제

.github/issue_template.md, .github/pull_request_template.md
- 이슈, PR 템플릿 업로드
- .github/issue_template.md
- .github/pull_request_template.md
=> Docs: Add issue and pull request templates

srcs/frontend/.env.example, srcs/frontend/package-lock.json, srcs/frontend/package.json, srcs/frontend/src/store/actions/gameActionHandler.js, srcs/frontend/src/views/components/login/loginButton.js, srcs/frontend/webpack.config.js
- hard coded url 방식에서 환경변수 사용하는 방식으로 변경
- npm package 'dotenv' 설치 및 webpack.DefinePlugin 사용
=> Feat: changed hard coded url to env variables

srcs/frontend/.editorconfig, srcs/frontend/src/app.js, srcs/frontend/src/store/actions/gameActionHandler.js, srcs/frontend/src/store/actions/singleGameActionHandler.js, srcs/frontend/src/store/actions/tournamentActionHandler.js, srcs/frontend/src/store/mutations.js, srcs/frontend/src/views/components/game/gameCanvas.js, srcs/frontend/src/views/components/game/gameOverModal.js, srcs/frontend/src/views/components/game/object/nickname.js, srcs/frontend/src/views/components/game/object/paddle.js, srcs/frontend/src/views/components/game/object/score.js, srcs/frontend/src/views/components/game/object/scoreSeperator.js, srcs/frontend/src/views/components/game/object/wall.js, srcs/frontend/src/views/components/game/tournamentBracketModal.js, srcs/frontend/src/views/components/main/gameCustomizationModal.js, srcs/frontend/src/views/components/main/gameModeCard.js, srcs/frontend/src/views/components/main/invalidNicknameModal.js, srcs/frontend/src/views/components/main/opponentWaitingModal.js, srcs/frontend/src/views/components/record/mainButton.js, srcs/frontend/src/views/components/tournamentRecord.js, srcs/frontend/src/views/utils/languagePack.js, srcs/frontend/src/views/utils/modalHandler.js, srcs/frontend/src/views/utils/router.js
- .editorconfig 에서 max-line-length를 120으로 설정
=> Update code formatting and style

srcs/game/game_module/BaseRoom.py, srcs/game/game_module/TournamentRoom.py
토너먼트 시 버그 일부 수정
+ 토너먼트가 종료될 경우 블록체인 요청이 여러 번 발생해 서버에 예외가 발생하던 버그를 수정
+ 전체 라운드가 끝나지 않은 상태에서 사용자가 나갈 경우 블록체인에 저장하지 않도록 수정
=> Fix: 게임 종료 시 다수의 동일한 블록체인 요청이 발생하던 버그 수정

srcs/docker-compose.yml
docker compose error 수정
docker compose 문법 에러 있어 작동하지 않는 현상 수정
=> Fix: docker compose error 수정, 이전 버전은 make 가 불가능함

Makefile
1. makefile 업 되지 않는 문제
2. 환경 변수 인식안된 문제
=> Fix : makefile up 되지 않는 치명적 문제 및 환경 변수

srcs/.env.example, srcs/game/blockchain/executeContract.py, srcs/game/config/settings.py
1. blockchain env 없이도 django container가 작동하도록 만들었습니다. 
2. django secret key 없이 django container가 작동하도록 만들었습니다. 
3. 이에 따라 env example 업데이트 했고, notino env도 업데이트 했습니다.
=> env 설정 없이도 django container가 작동하도록 만듦.

srcs/frontend/src/views/components/main/gameCustomizationModal.js
makeRandomName 삭제하였음.
임시 intraId를 생성하는 부분을 삭제하였다.
=> Fix: makeRandomName 삭제

srcs/game/game_module/BaseRoom.py, srcs/game/game_module/GameRoom.py, srcs/game/game_module/GameStateManager.py, srcs/game/game_module/TournamentRoom.py
=> Game refactoring 1

srcs/frontend/src/store/actions/gameActionHandler.js, srcs/frontend/src/store/actions/singleGameActionHandler.js, srcs/frontend/src/store/actions/tournamentActionHandler.js, srcs/game/game_module/game_queue.py, srcs/game/game_module/tournament_queue.py
userFullEvent에서 socketId를 포함하도록 변경
socketId를 포함하여 동일한 intra 로그인을 한 경우에도 게임이 가능하도록 수정
=> Game debug 5

srcs/frontend/src/store/actions.js, srcs/frontend/src/store/actions/singleGameActionHandler.js
언어를 바꿔도 html의 lang 어트리뷰트는 수정되지 않았던 오류를 고쳤습니다.
=> 55 bug 언어를 바꿨을때 html의 lang 어트리뷰트가 바뀌지 않는 오류

srcs/frontend/src/views/components/main.js, srcs/frontend/src/views/components/main/languageSelector.js, srcs/frontend/src/views/components/record/mainButton.js, srcs/frontend/src/views/components/record/tournamentRecordButton.js, srcs/frontend/src/views/components/tournamentRecord.js
- NavBar 레이아웃 구성 변경
- Tournament Record 버튼과 Language Selector 가 같은 수평선 상에 위치하도록 코드를 변경
=> Refactor navbar layout in main.js and tournamentRecord.js

srcs/frontend/src/views/components/main.js
- Language가 영어인 경우 화면 크기를 줄이면 GameMode 카드의 사이즈가 달라지는 버그 수정
=> Update game mode card layout

srcs/frontend/src/app.js, srcs/frontend/src/library/store.js, srcs/frontend/src/store/actions.js, srcs/frontend/src/store/actions/gameActionHandler.js, srcs/frontend/src/store/actions/singleGameActionHandler.js, srcs/frontend/src/store/actions/tournamentActionHandler.js, srcs/frontend/src/store/mutations.js, srcs/frontend/src/views/components/game/gameOverModal.js, srcs/frontend/src/views/components/game/tournamentBracketModal.js, srcs/frontend/src/views/components/main/languageSelector.js, srcs/frontend/src/views/components/main/opponentWaitingModal.js, srcs/frontend/src/views/components/tournamentRecord.js, srcs/frontend/src/views/utils/router.js
=> Comment: log 주석 처리

srcs/game/game_module/BaseRoom.py, srcs/game/game_module/GameStateManager.py, srcs/game/game_module/game_ctl.py, srcs/game/game_module/socketio_server.py
게임 로직 개선
공이 충돌 시에만 공 위치와 속도를 전송하도록 하여 네트워크 트래픽 문제 개선
=> feat: game 전송 logic 일부 변경

srcs/game/game_module/BaseRoom.py
공 이벤트명 변경과 공 신호가 계속하여 가던 버그 수정
=> New game logic 1

srcs/game/blockchain/executeContract.py
=> HOTFIX : 블록체인 안돌아가던 문제 후덜덜

srcs/frontend/src/store/actions/gameActionHandler.js
=> Fix/fix ball rendering logic - 자신의 패들 먼저 랜더링 하는 방식으로 수정

srcs/frontend/src/store/actions/tournamentActionHandler.js
토너먼트 플레이시, 패들의 위치가 제대로 초기화되지 않는 버그 고쳤습니다.
=> Fix: 패들 초기화 버그 수정

srcs/frontend/src/store/actions/singleGameActionHandler.js, srcs/frontend/src/store/actions/tournamentActionHandler.js, srcs/frontend/src/views/components/game/audioButton.js, srcs/frontend/src/views/components/main.js, srcs/frontend/src/views/components/main/logoutButton.js, srcs/frontend/src/views/utils/languagePack.js
=> Feature: logout button 추가

srcs/frontend/src/static/css/styles.css, srcs/frontend/src/static/css/tournamentBracketStyle.css, srcs/frontend/src/views/components/game.js, srcs/frontend/src/views/components/game/gameCanvas.js, srcs/frontend/src/views/components/game/gameScoreBoard.js
=> Fix/fix textmesh lag - 스코어보드 HTML 방식으로 수정

srcs/frontend/src/views/components/game/gameCanvas.js
- 사용자가 패들의 키보드 인풋을 더 자주 넣을 수 있게 수정
=> Fix: Update keyboard input delay in gameCanvas.js
